### ISSUE TITLE
[Question]1.16.2 optifine compatible with fabric

### ISSUE THREAD

**Issue by LegendLZD** [Fox2Code/FabricZero#6]
1.16.2 optifine hasn't been released yet.But I have a question
As you know,optifabric stopped updating now.
So do you make optifine 1.16.2 compatible with fabric?

**Comment by Fox2Code** [comment]
My mod does not port OptiFabric to work on 1.16.2
In fact, mods can't do that due of how Fabric loads mods (Fabric don't load mods if the version does not match)

But maybe if Optifine 1.16.2 get released I will be able to port OptiFabric to 1.16.2
https://github.com/modmuss50/OptiFabric/blob/master/src/main/resources/fabric.mod.json
```JSON
  "depends": {
    "fabricloader": ">=0.8.8",
    "minecraft": "1.16.1"
  }
```
/\\ This part of the JSON in OptiFabric prevent Minecraft of booting if the version is not 1.16.1
But you should maybe use https://github.com/jellysquid3/sodium-fabric because it's more compatible with most mods and easier to work with
Since Sodium is new it doesn't have as many features as Optifine but the mod works very well

**Comment by LegendLZD** [comment]
So if optifine 1.16.2 get released you will continue making optifabric to let it work on 1.16.2 instead of making optifine compatible directly with fabric,right?

**Comment by Fox2Code** [comment]
Fabric use yarn -> https://github.com/FabricMC/yarn
Which Optifine does not support directly and also Optifine is closed source meaning you can't edit Optifine code like that and made Optifine compatible  
The dev who made OptiFabric is very talented but stoped to made it because it was too time-consuming for him  
If I "port" OptiFabric it would probably be just to make it launch on 1.16.2  
If everyone is switching to Sodium is because it's easier to support, cause fewer compatibility issues, and is opensource.

For now, only the dev of Optifine can make Optifine directly compatible with fabric.

**Comment by LegendLZD** [comment]
Ok,I know
